### ISSUE TITLE
Request: Context menu for sidebar

### ISSUE THREAD

**Issue by ChildishGiant** [takase1121/lite-contextmenu#1]
This'd just have new file and new folder on it

**Comment by takase1121** [comment]
That was my original plan, but it is incredibly hard to implement. In short - there are no way to check if you clicked in the treeview or not, not even mentioning whether you clicked on a file or a folder.

I can export the contextmenu, but you will need to modify treeview.lua to make it work.

**Comment by ChildishGiant** [comment]
I suppose you could host a modified version of treeview in this repo but I see how that could be out of scope

**Comment by takase1121** [comment]
I plan to do that if I have time.

**Comment by takase1121** [comment]
I did it, now treeview.lua with context menu enabled is uploaded here.
