### ISSUE TITLE
Error when installing lite-contextmenu

### ISSUE THREAD

**Issue by TheKing0x9** [takase1121/lite-contextmenu#2]
**Describe the problem**
When installing lite-contextmenu, lite throws an error at Line 233 in contextmenu.lua, stating that it can't compare number with nil. This hinders all mouse clicks in the editor, with the same error being thrown everytime mouse is clicked

**Steps to reproduce**
1. Install the required dependencies.
2. Install lite-contextmenu.
3. Restart the editor
4. See the error

**Additional Information**
1. Tested on Windows.
2. Lite-XL version 1.16

**Suggested Fixes**
Changing line 233 from
```lua
  if node.hovered_scroll_button > 0 then
```
to
```lua
  if node.hovered_scroll_button then
```
fixes the problem and makes the context menu work again

**Comment by takase1121** [comment]
My plugins works with the `dev` branch, so these little problems that isn't enforced by plugin versioning occurs. If you don't mind, please PR the fix.

**Comment by TheKing0x9** [comment]
Will do!
