### ISSUE TITLE
New File in Tree view doesn't create files

### ISSUE THREAD

**Issue by TheKing0x9** [takase1121/lite-contextmenu#4]
**Describe the issue**
The New File menu item in treeview in lite(-xl) uses the open file dialog for creating new files, which sends a message that inexistent file can't be opened instead of creating new files.

**Steps to reproduce**
- Right Click on a directory in lite-xl
- Select new file
- Enter a name
- See the error

** Tested On **
- Windows
- Lite XL v1.16

** Suggested fixes**
I have a fix for this ready that works on lite(-xl). Although on lite, it fails with an error of cannot open doc in locked node 
The fix works by changing
```lua
command.perform "core:open-file"
```
to

```lua
core.command_view:enter("New filename", function(name)
      local doc = core.open_doc()
      core.root_view:open_doc(doc)
      doc:save(name)
    end)
```

Both lite and lite-xl use this to create project module iinternally, but for some reason, this works in lite-xl but not in lite

**Comment by takase1121** [comment]
Interesting, this is also one problem I stumbled upon that I can't fix. I've yet to find a way to fix it in lite.

**Comment by TheKing0x9** [comment]
So should I PR the fix for lite-xl at least?

**Comment by takase1121** [comment]
> So should I PR the fix for lite-xl at least?

Yes, thank you! For lite, jusy open a new doc for fallback.
